# movies.csv数据分析目标
数据列备忘:https://classroom.udacity.com/nanodegrees/nd002-cn-basic/parts/a2741c91-dadf-4e85-89bd-d39a5574047c/modules/05f87888-bdf0-4be5-bd56-b9d245f979d1/lessons/6c6e2644-0c8a-4fde-a739-bebad85886ef/concepts/26b53161-875c-47dc-9fb3-387b7cb43d0e
id：标识号
imdb_id：IMDB 标识号
popularity：在 Movie Database 上的相对页面查看次数
budget：预算（美元）
revenue：收入（美元）
original_title：电影名称
cast：演员列表，按 | 分隔，最多 5 名演员
homepage：电影首页的 URL
director：导演列表，按 | 分隔，最多 5 名导演
tagline：电影的标语
keywords：与电影相关的关键字，按 | 分隔，最多 5 个关键字
overview：剧情摘要
runtime：电影时长
genres：风格列表，按 | 分隔，最多 5 种风格
production_companies：制作公司列表，按 | 分隔，最多 5 家公司
release_date：首次上映日期
vote_count：评分次数
vote_average：平均评分
release_year：发行年份
budget_adj：根据通货膨胀调整的预算（2010 年，美元）
revenue_adj：根据通货膨胀调整的收入（2010 年，美元）


需回答问题：
问题1：电影类型是如何随着时代变化而变化的?
问题2：环球影业(Universal Studios/Universal Pictures)和派拉蒙影业(Paramount Pictures)的电影之前数据有什么区别?
问题3：和非小说改编的电影相比，基于小说改编的电影表现得怎么样?

我的问题:
大片烂片泛滥的时代,我比较好奇用户风评与影片盈利是否存在着正向关系,因此计划做下面的探究.
问题4:电影盈利和观众评分之间是怎么变化的?

In [1]:
import pandas as pd
import numpy as np
import exceptions
from __future__ import division
import matplotlib.pyplot as plt
%matplotlib inline

#读原始CSV
movie_df=pd.read_csv('movies.csv',encoding='utf-8')
movie_df.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015/5/13,6185,7.1,2015,137999939.3,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015/3/18,2480,6.3,2015,101199955.5,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015/12/15,5292,7.5,2015,183999919.0,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015/4/1,2947,7.3,2015,174799923.1,1.385749e+09

观察上表,id和imdb_id均能唯一定位一部影片,original_title和tagline是影片的标题,初步探索与四个问题相关的数据列:
问题1：电影类型是如何随着时代变化而变化的?(release_year,genres需要先做拆分)
问题2：环球影业(Universal Studios/Universal Pictures)和派拉蒙影业(Paramount Pictures)的电影之前数据有什么区别?(production_companies,需要做拆分)
问题3：和非小说改编的电影相比，基于小说改编的电影表现得怎么样?
(keywords,需要做拆分,评估其revenue,vote_average)

问题4:不同年代电影盈利和观众评分之间是怎么变化的?
(release_year,genres需要先做拆分,revenue,budget)

初步结论:在使用tableau分析之前,需要将原始数据转化为三张可以直接分析的datasheet:按genres分列的一张表,按keywords拆分的一张表,按production_companies拆分的一张表.

In [2]:
#查看数值列是否存在缺失记录或者异常值
movie_df.describe()

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
count,10866.000000,10866.000000,1.086600e+04,1.086600e+04,10866.000000,10866.000000,10866.000000,10866.000000,1.086600e+04,1.086600e+04
mean,66064.177434,0.646441,1.462570e+07,3.982332e+07,102.070863,217.389748,5.974922,2001.322658,1.755104e+07,5.136436e+07
std,92130.136561,1.000185,3.091321e+07,1.170035e+08,31.381405,575.619058,0.935142,12.812941,3.430616e+07,1.446325e+08
min,5.000000,0.000065,0.000000e+00,0.000000e+00,0.000000,10.000000,1.500000,1960.000000,0.000000e+00,0.000000e+00
25%,10596.250000,0.207583,0.000000e+00,0.000000e+00,90.000000,17.000000,5.400000,1995.000000,0.000000e+00,0.000000e+00
50%,20669.000000,0.383856,0.000000e+00,0.000000e+00,99.000000,38.000000,6.000000,2006.000000,0.000000e+00,0.000000e+00
75%,75610.000000,0.713817,1.500000e+07,2.400000e+07,111.000000,145.750000,6.600000,2011.000000,2.085325e+07,3.369710e+07
max,417859.000000,32.985763,4.250000e+08,2.781506e+09,900.000000,9767.000000,9.200000,2015.000000,4.250000e+08,2.827124e+09

数值列的count一致,均为10866,说明无空值情况.但是电影时长runtime最小值有为零的,这个按照常识来讲,不合理.因此调查一下这部分数据.

In [3]:
#检查,runtime为0的电影是否存在,记录是否完整
lookuperrer_df=movie_df[movie_df['runtime']== 0]
lookuperrer_df

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
92,370687,tt3608646,1.876037,0,0,Mythica: The Necromancer,Melanie Stone|Adam Johnson|Kevin Sorbo|Nicola ...,http://www.mythicamovie.com/#!blank/y9ake,A. Todd Smith,NaN,...,Mallister takes Thane prisoner and forces Mare...,0,Fantasy|Action|Adventure,Arrowstorm Entertainment|Camera 40 Productions...,2015/12/19,11,5.4,2015,0.000,0.0
334,361931,tt5065822,0.357654,0,0,Ronaldo,Cristiano Ronaldo,http://www.ronaldothefilm.com,Anthony Wonke,Astonishing. Intimate. Definitive.,...,Filmed over 14 months with unprecedented acces...,0,Documentary,"On The Corner Films|We Came, We Saw, We Conque...",2015/11/9,80,6.5,2015,0.000,0.0
410,339342,tt2948712,0.097514,0,0,Anarchy Parlor,Robert LaSardo|Jordan James Smith|Sara Fabel|T...,NaN,Kenny Gage|Devon Downs,NaN,...,Six young college hopefuls vacationing and par...,0,Horror,NaN,2015/1/1,15,5.6,2015,0.000,0.0
445,353345,tt3800796,0.218528,0,0,The Exorcism of Molly Hartley,Sarah Lind|Devon Sawa|Gina Holden|Peter MacNei...,NaN,Steven R. Monroe,NaN,...,Taking place years after The Haunting of Molly...,0,Horror,WT Canada Productions,2015/10/9,52,5.0,2015,0.000,0.0
486,333653,tt4058368,0.176744,0,0,If There Be Thorns,Heather Graham|Jason Lewis|Rachael Carpani|Mas...,NaN,Nancy Savoca,NaN,...,The third installment in V.C. Andrews’ bestsel...,0,TV Movie|Drama,A+E Studios|Jane Startz Productions,2015/4/5,11,5.4,2015,0.000,0.0
595,341051,tt2914740,0.028725,0,0,Deep Dark,Sean McGrath|Denise Poirier|Anne Sorce|Tabor H...,http://deepdarkmovie.com,Michael Medaglia,NaN,...,Fantasy - A failed sculptor discovers a strang...,0,Horror,NaN,2015/1/1,11,4.6,2015,0.000,0.0
616,325843,tt4333210,0.026797,0,0,The Outfield,Cameron Dallas|Hamilton Nash Grier|Olivia Stuc...,NaN,Michael Goldfine,NaN,...,The film follows a trio of varsity baseball pl...,0,Drama|Comedy,NaN,2015/11/10,20,6.6,2015,0.000,0.0
1241,296370,tt3024964,0.135376,0,0,Dance-Off,Kathryn McCormick|Shane Harper|Finola Hughes|C...,NaN,NaN,NaN,...,DANCE-OFF is a tongue-in-cheek family comedy s...,0,Romance|Music|Comedy,NaN,2014/1/1,18,5.7,2014,0.000,0.0
1289,286372,tt1791681,0.037459,3250000,0,Treehouse,J. Michael Trautmann|Dana Melanie|Daniel Fredr...,http://www.imdb.com/title/tt1791681/,Michael G. Bartlett,No kids allowed,...,A teenage boy discovers the perpetrators of se...,0,Thriller|Horror|Mystery,Tiberius Film,2014/10/20,16,3.4,2014,2993545.915,0.0
1293,286256,tt3134058,0.036904,0,0,Tim Maia,Robson Nunes|Babú Santana|Alinne Moraes|Cau? R...,NaN,Mauro Lima,Original language PORTUGUESE,...,"Biopic of Brazilian singer Tim Maia, from his ...",0,Documentary|Drama|Music,Globo Filmes,2014/10/30,14,6.0,2014,0.000,0.0
1849,18247,tt1212986,0.120350,0,0,Spectacular!,Nolan Gerard Funk|Jesse Moss|Britt Irvin|Tammi...,NaN,Robert Iscove,NaN,...,"A high school choir is fading in popularity, a...",0,Drama|Music,NaN,2009/2/16,13,5.2,2009,0.000,0.0
2315,48373,tt1274296,0.171615,0,0,Listen to Your Heart,Alexia Rasmussen|Kent Moran|Cybill Shepherd|Sh...,http://www.listentoyourheartfilm.com/,NaN,One song can change your life.,...,Danny Foster doesn't have much: an apartment a...,0,Drama|Music|Romance,NaN,2010/8/14,29,7.3,2010,0.000,0.0
2370,127717,tt1525359,0.081892,0,0,Freshman Father,Britt Irvin|Merrilyn Gann|Barbara Tyson|Anthon...,NaN,Michael Scott,NaN,...,NaN,0,NaN,NaN,2010/6/5,12,5.8,2010,0.000,0.0
3329,20414,tt1077026,0.082898,0,0,"Grande, grosso e Verdone",Carlo Verdone|Claudia Gerini|Eva Riccobono|Vit...,NaN,Carlo Verdone,NaN,...,No overview found.,0,Family,Filmauro,2008/3/7,35,5.3,2008,0.000,0.0
3794,58253,tt1588335,0.183134,0,0,"Toi, moi, les autres",Le?la Bekhti|Benjamin Siksou|Cécile Cassel|Cha...,http://www.google.fr/m/url?ei=e3BxTcjeLMqB8wP6...,Audrey Estrougo,NaN,...,NaN,0,Music|Romance,NaN,2011/2/22,17,5.2,2011,0.000,0.0
3857,289097,tt1288636,0.095583,0,0,Cell 213,Bruce Greenwood|Eric Balfour|Michael Rooker|De...,NaN,Stephen Kay,NaN,...,Cocky young attorney Michael Gray finds himsel...,0,Horror,Access Motion Pictures,2011/6/10,13,5.2,2011,0.000,0.0
3884,105885,tt1754944,0.045198,0,0,eCupid,Houston Rhines|Andy Anderson|John Callahan|Gal...,NaN,J.C. Calciano,NaN,...,From the director of Is It Just Me? comes this...,0,Romance,NaN,2011/6/23,12,4.6,2011,0.000,0.0
4063,28004,tt0359639,0.371510,6000000,0,Madea's Family Reunion,Tyler Perry|Blair Underwood|Lynn Whitfield|Bor...,NaN,Tyler Perry,NaN,...,"Just as the southern matriarch, Madea buries h...",0,Comedy,NaN,2002/1/25,49,5.9,2002,7273568.362,0.0
4138,44266,tt0242953,0.035895,0,0,A Time for Dancing,Larisa Oleynik|Shiri Appleby|Peter Coyote|Patr...,NaN,Peter Gilbert,NaN,...,"Their love of dance, and their friendship, is ...",0,Drama|Music,NaN,2002/9/6,14,7.5,2002,0.000,0.0
4829,110490,tt1910605,0.140016,0,0,Rags,Keke Palmer|Avan Jogia|Drake Bell|Burkely Duff...,NaN,Bille Woodruff,NaN,...,"Rags follows the story of Charlie Prince, an o...",0,TV Movie|Comedy|Drama,NaN,2012/5/28,24,5.7,2012,0.000,0.0
4944,158150,tt2395247,0.026459,0,0,How to Fall in Love,Brooke D'Orsay|Eric Mabius|Jody Thompson|Gina ...,NaN,Mark Griffiths,NaN,...,"An accountant, who never quite grew out of his...",0,Comedy|Romance|TV Movie,Annuit Coeptis Entertainment Inc.|Annuit Coept...,2012/7/21,11,4.7,2012,0.000,0.0
5216,28003,tt0427481,0.073665,0,0,Madea's Class Reunion,Tyler Perry|Chandra Currelley|Cheryl Pepsii Ri...,NaN,Tyler Perry,NaN,...,"Madea is traveling to the Pandora Hotel, where...",0,Comedy|Music,NaN,2003/6/25,12,6.9,2003,0.000,0.0
5695,224815,tt2881698,0.417739,0,0,Skinwalker Ranch,Steve Berg|Kyle Davis|Erin Cahill|Jon Gries|De...,NaN,Devin McGinn,NaN,...,In 2010 “Skinwalker Ranch” gained media atten...,0,Thriller|Horror|Science Fiction,DeepStudios,2013/10/30,27,4.3,2013,0.000,0.0
5920,248842,tt2364006,0.165765,0,0,The Food Guide to Love,Richard Coyle|Leonor Watling|Ginés García Mill...,NaN,Dominic Harari|Teresa Pelegri,NaN,...,A dysfunctional love story about an Irish food...,0,Romance|Comedy,Haut et Court|Parallel Film Productions|Fox In...,2013/12/18,12,5.6,2013,0.000,0.0
5938,191562,tt2436516,0.147188,0,0,Go Goa Gone,Saif Ali Khan|Anand Tiwari|Vir Das|Pooja Gupta,NaN,Krishna D.K.|Raj Nidimoru,NaN,...,"A rave party off the coast of Goa, goes horrif...",0,Comedy|Horror,Eros International,2013/5/10,16,5.3,2013,0.000,0.0
5992,173847,tt2343371,0.096455,0,0,Amiche da morire,Claudia Gerini|Cristiana Capotondi|Sabrina Imp...,NaN,Giorgia Farina,NaN,...,Three very different women who are hiding a se...,0,Romance|Crime|Comedy,NaN,2013/3/7,30,5.5,2013,0.000,0.0
6040,202604,tt3043194,0.011798,0,0,The Vatican Exorcisms,Joe Marino,NaN,Joe Marino,The public were never meant to know,...,Documentary following US film-maker Joe Marino...,0,Horror|Documentary|Mystery,NaN,2013/5/29,10,4.7,2013,0.000,0.0
6383,26985,tt0405615,0.371630,2000000,0,The 12 Dogs of Christmas,Jordan-Claire Green|Tom Kemp|Susan Wood|Adam H...,NaN,Kieth Merrill,NaN,...,This holiday tale has all the elements of a cl...,0,Drama|Family,NaN,2005/11/1,11,4.7,2005,2233126.579,0.0
6552,13739,tt0448245,0.006440,0,0,Quatre étoiles,José Garcia|Isabelle Carré|Renée Le Calm|Fran?...,NaN,Christian Vincent,NaN,...,No overview found.,0,Comedy,NaN,2005/1/1,15,5.9,2005,0.000,0.0
6934,13713,tt0477988,0.071872,0,0,Jean-Philippe,Fabrice Luchini|Johnny Hallyday|Jackie Berroye...,NaN,Laurent Tuel,NaN,...,No overview found.,0,Comedy,Fidélité Productions|StudioCanal|TF1 Films Pro...,2006/4/5,26,5.6,2006,0.000,0.0
8874,46406,tt0248185,0.069903,0,0,Mission Kashmir,Sanjay Dutt|Hrithik Roshan|Preity Zinta|Jackie...,NaN,Vidhu Vinod Chopra,NaN,...,A police officer adopts the son and sole survi...,0,Action|Drama|Foreign,NaN,2000/10/27,10,5.7,2000,0.000,0.0

按影片名谷歌搜索,发现对应影片存在,但是其预算和时长等数据严重失真因此清除这些无用条目.

In [4]:
#清理runtime为零的数据列
movie_newdf=movie_df[movie_df['runtime']>0]
movie_newdf.describe()

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
count,10835.000000,10835.000000,1.083500e+04,1.083500e+04,10835.000000,10835.000000,10835.000000,10835.000000,1.083500e+04,1.083500e+04
mean,65747.954776,0.647757,1.466651e+07,3.993726e+07,102.362898,217.952100,5.976253,2001.296078,1.760010e+07,5.151132e+07
std,91816.027384,1.001158,3.094791e+07,1.171513e+08,30.946957,576.345266,0.935051,12.819389,3.434284e+07,1.448131e+08
min,5.000000,0.000065,0.000000e+00,0.000000e+00,2.000000,10.000000,1.500000,1960.000000,0.000000e+00,0.000000e+00
25%,10586.500000,0.208561,0.000000e+00,0.000000e+00,90.000000,17.000000,5.400000,1995.000000,0.000000e+00,0.000000e+00
50%,20556.000000,0.384763,0.000000e+00,0.000000e+00,99.000000,38.000000,6.000000,2006.000000,0.000000e+00,0.000000e+00
75%,75036.000000,0.715444,1.500000e+07,2.417286e+07,112.000000,146.000000,6.600000,2011.000000,2.094485e+07,3.389248e+07
max,417859.000000,32.985763,4.250000e+08,2.781506e+09,900.000000,9767.000000,9.200000,2015.000000,4.250000e+08,2.827124e+09

从上述数据看到,剩余影片中runtime最小时长为2分钟,看起来不太合理,拎出来检查下

In [5]:
#检查,runtime为2分钟的电影是否存在,记录是否完整
lookuperrer_df=movie_newdf[movie_newdf['runtime']==2]
lookuperrer_df

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
4883,142563,tt2309977,0.078472,0,0,Fresh Guacamole,NaN,NaN,PES,NaN,...,In this follow-up to his stop-motion hit Weste...,2,Animation,NaN,2012/3/2,29,7.9,2012,0.0,0.0
4890,126909,tt2219564,0.083202,0,0,Cousin Ben Troop Screening,Jason Schwartzman,http://www.funnyordie.com/videos/fc132ce8b2/co...,Wes Anderson,NaN,...,Cousin Ben hosts a screening of Wes Anderson's...,2,NaN,NaN,2012/1/1,14,7.0,2012,0.0,0.0
7905,13924,tt0086855,0.647261,0,0,The Adventures of André and Wally B.,NaN,NaN,Alvy Ray Smith,NaN,...,There's nothing like a restful nap in a pleasa...,2,Animation,Lucasfilm|Pixar Animation Studios,1984/12/17,32,5.3,1984,0.0,0.0
10550,13925,tt0091455,0.306425,0,0,Luxo Jr.,NaN,http://www.pixar.com/short_films/Theatrical-Sh...,John Lasseter,NaN,...,A baby lamp finds a ball to play with and it's...,2,Animation|Family,Pixar Animation Studios,1986/8/17,81,7.3,1986,0.0,0.0
10754,3171,tt0064064,0.002757,0,0,Bambi Meets Godzilla,NaN,NaN,Marv Newland,NaN,...,"Bambi is nibbling the grass, unaware of the up...",2,Animation|Comedy,NaN,1969/1/1,12,5.6,1969,0.0,0.0

抽样检查Cousin Ben Troop Screening,发现确实存在,那么runtime的异常清理就到这里了,movie_newdf就为后继分析的基线数据.

In [6]:
#将清理了runtime为零数据后的movie_newdf梳理keywords列分类为'based on novel'和非'based on novel'两类
movie_cleardf=movie_newdf
movie_cleardf.loc[movie_cleardf['keywords'].str.contains("novel",na=False), 'keywords']='based on novel'
movie_cleardf.loc[movie_cleardf['keywords'].str.contains("novel",na=False)==False, 'keywords']='not based on novel'
#将清理了runtime为零数据后的movie_newdf存入movies_cleared.xlsx的'movie_clearbase'页签
writer=pd.ExcelWriter('movies_cleared.xlsx')
movie_cleardf.to_excel(writer,'movie_clearbase', na_rep=0,encoding='utf-8')

d:\Python\Anaconda2\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [7]:
#定义按关键字对指定列分列处理函数
def splitcolumn(df,colname,keywords):
    try:
        newdf=df
        newcolname='new'+colname
        s=newdf[colname].str.split(keywords).apply(pd.Series,1).stack()
        s.index=s.index.droplevel(-1)
        s.name=newcolname
        del newdf[colname]
        newdf=newdf.join(s)
        return newdf        
    except(ZeroDivisionError,ValueError,TypeError),e:
        print e

In [8]:
#梳理genres列,将电影类型分列存储,存入movies_cleared.xlsx的'movie_genressplit'页签
temp_df=splitcolumn(movie_newdf,'genres','|')
temp_df.to_excel(writer,'movie_genressplit', na_rep=0,encoding='utf-8')

In [9]:
#梳理production_companies列,将电影厂家分列存储,存入movies_cleared.xlsx的'movie_productionsplit'页签
product_df=splitcolumn(movie_newdf,'production_companies','|')
product_df.to_excel(writer,'movie_productionsplit', na_rep=0,encoding='utf-8')
#保存writer=pd.ExcelWriter('movies_cleared.xlsx')所建文件
writer.save()

In [10]:
product_df.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,keywords,overview,runtime,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj,newproduction_companies
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,not based on novel,Twenty-two years after the events of Jurassic ...,124,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09,Universal Studios
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,not based on novel,Twenty-two years after the events of Jurassic ...,124,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09,Amblin Entertainment
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,not based on novel,Twenty-two years after the events of Jurassic ...,124,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09,Legendary Pictures
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,not based on novel,Twenty-two years after the events of Jurassic ...,124,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09,Fuji Television Network
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,not based on novel,Twenty-two years after the events of Jurassic ...,124,2015/6/9,5562,6.5,2015,137999939.3,1.392446e+09,Dentsu